version: 2

sphinx:
    builder: html
    configuration: pyatoa/docs/conf.py

python:
    version: 3.7
    install:
        - requirements: pyatoa/docs/requirements.txt
        - requirements: requirements.txt
        - method: setuptools
          path: .

conda:
    environment: pyatoa/docs/environment.yml
