name: pyatoa
channels:
    - conda-forge
    - defaults
dependencies:
    - pip
    - obspy
    - pyasdf
    - pandas
    - cartopy
    - pyyaml
    - pypdf2
    - pip:
      - git+https://github.com/adjtomo/pyflex.git
      - git+https://github.com/adjtomo/pyadjoint.git
      - git+https://github.com/adjtomo/pysep.git
      - -e .
       
