name: Feature request
description: Request a new feature for Pyatoa
title: "Wrapper for <module-name>"
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Please replace `<module-name>` in the issue title and the description with the name of the requested module and add the description of the module.
  - type: textarea
    id: which-module
    attributes:
      label: Description of the desired module
      description: Please be as detailed as you can in your description. If possible, include an example of how you would like to use this feature (even better if it's a code example).
    validations:
      required: true
  - type: dropdown
    id: help
    attributes:
      label: Are you willing to help implement and maintain this feature?
      description: |
        Every feature we add is code that we will have to maintain and keep updated. This takes a lot of effort.
        If you are willing to be involved in the project and help maintain your feature, it will make it easier for us to accept it.
      options:
        - "No"
        - "Yes"
        - "Maybe"
    validations:
      required: true
