name: pyatoa

channels:
    - conda-forge
dependencies:
    - python=3.7
    - basemap=1.2.2
    - obspy=1.2.2
    - matplotlib=3.1.1
    - pyasdf=0.7.2
    - pandas=1.1.0
    - pyyaml=5.3.1
    - proj4=5.2.0
    - pip
      - git+https://github.com/bch0w/pyflex.git@749f0cdd81a4505c418d484d6db29d1f6a5aa328#egg=return_reject_windows
      - git+https://github.com/krischer/pyadjoint.git@8a20e47bdd2796ff1e8266cf5a9d2fce8e084e9a#egg=master
