name: pyatoa

channels:
    - conda-forge
dependencies:
    - python=3.7
    - basemap=1.2.0
    - obspy=1.2.2
    - matplotlib=3.1.1
    - pyasdf=0.7.2
    - pandas=1.1.0
    - pyyaml=5.3.1
    - proj4=5.2.0
    - pip
    - pip:
      - -e git+https://github.com/bch0w/pyflex.git#egg=return_reject_windows
      - -e git+https://github.com/krischer/pyadjoint.git#egg=master
